healthcheck:
    url: ""
    interval_seconds: 0
regions: {}
group_names:
    proxy: ""
    auto: ""
    other: ""
groups:
    - name: 手动选择
      type: select
    - name: 自动选择
      type: url-test
      url: https://www.gstatic.com/generate_204
      interval: 300
    - name: test
      type: url-test
      url: https://www.gstatic.com/generate_204
      interval: 300
      provider: test
