healthcheck:
  url: https://www.gstatic.com/generate_204
  interval_seconds: 300
regions: {}
group_names:
  proxy: PROXY
  auto: AUTO
  other: DIRECT
groups:
  - name: PROXY
    type: select
  - name: AUTO
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
