proxies: []
proxy-groups: []
rule-providers:
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
    proxy: DIRECT
  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
    proxy: DIRECT
  cncidr:
    type: http
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
    proxy: DIRECT
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
    proxy: DIRECT
  lancidr:
    type: http
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
    proxy: DIRECT
rules:
  - DOMAIN,cn.bing.com,DIRECT
  - DOMAIN,api.cloudflare.com,DIRECT
  - DOMAIN,www.gstatic.com,DIRECT
  - DOMAIN,gst.prod.dl.playstation.net,DIRECT
  - DOMAIN-SUFFIX,douyin.com,DIRECT
  - GEOSITE,openai,PROXY
  - GEOSITE,anthropic,PROXY
  - GEOSITE,google-gemini,PROXY
  - GEOSITE,geolocation-!cn,AUTO
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,cn,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,direct,DIRECT
  - MATCH,AUTO
